sudo: false

language: scala

scala:
- 2.11.7

jdk:
- openjdk7
- oraclejdk7
- oraclejdk8

# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

script:
    - sbt test
    - sbt 'project benchmark' 'jmh:run -i 3 -wi 3 -f1 -t1'

notifications:
  slack:
    secure: i2alROj2iovxvJIN6bX8QipZGnGC5rwLFkejkac5DRlz1wTRmQlxbiMevH1SZ6vRWkEqdTnMwJXK3iq9CLFKDzhbkho64cBK9oaoSghaZLwebVuBGWRsxySvAWe7X5gIwDy7tWnlmiqp4SMSq+QxgROCKjtyFWnvyVOVoFXtpI2nnDyVb+ViweKy3EFUsIAmN0Jh1jlsKqJW0NpMZYLD/VeQpwm9TDaLVu0YpuhSPcGsvras5gWT5eymPZwwUnzQBWkoLyJCCFS3vMO1zZofK9Xcg0nAc0JaxUlY8+6bD9SFaYk/5WcfJnuTtnuA6fR4npejrihQ+K/79G5IZLP8XVcOgJETa9AMuqYldb2cgoXDxCcfTLHUWXUpqBvkECwdd0JXTzo3sytH6j7lKOcIUbSCbXeVfn5Ozqf2QmtkITr6E2mAT3FNr45DrL6zRJ5WEWgyU0sMrGYAcmDNvnlROUR5aBVI101PJqg9kwC0yVQ4DraTH3FG8Pv5ArVfFdArQjeir1WSZEInBQOYLT+DzJ7OLJSHC51tpeparNR7sqbrUKA8iyQJSYD4OoKkw7c7flyMmKH1dMS+ObczHVEyNAl+3d09V8Sei+KK29Fu39uoA16SE3Jj5Vok+kNoM+/osFJdk4zfsPcB3NprzxrvKEk8+W6tp0K+xnBP8TneB0Q=
